### PR TITLE
FIX: Decimal insert from JSON

### PR DESCRIPTION
**Pull request by Zarathustra2**
@sofakingworld 

It seems we cannot insert Decimal values anymore. Is there any setting in clickhouse which can be activated so that decimal values can be inserted as string? 

I don't really like casting decimal values to float. 

```
mpro-2.local :) create table foobar ( field4 Decimal32(4)) engine = Memory;

CREATE TABLE foobar
(
    `field4` Decimal32(4)
)
ENGINE = Memory

Query id: a2f8142f-07a6-4785-a214-bfec6221716f

Ok.

0 rows in set. Elapsed: 0.010 sec.

mpro-2.local :) insert into foobar FORMAT JSONEachRow {"field4": "1"}

INSERT INTO foobar FORMAT JSONEachRow

Query id: e29f0614-b7f4-4159-af15-e7ab97a6b332

Ok.
Exception on client:
Code: 27. DB::ParsingException: Cannot parse input: expected ',' before: '"1"}': While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from query: (at row 1)
. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)

mpro-2.local :) insert into foobar FORMAT JSONEachRow {"field4": 1}

INSERT INTO foobar FORMAT JSONEachRow

Query id: 9f40dd14-2e4a-4c21-8bd0-515672e10e59

Ok.

1 row in set. Elapsed: 0.003 sec.

mpro-2.local :) insert into foobar FORMAT JSONEachRow {"field4": 1.0}

INSERT INTO foobar FORMAT JSONEachRow

Query id: 80793946-c2c1-4a2f-8c97-691c6d3d2414

Ok.

1 row in set. Elapsed: 0.003 sec.

mpro-2.local :) insert into foobar FORMAT JSONEachRow {"field4": "1"}

INSERT INTO foobar FORMAT JSONEachRow

Query id: a4552108-677b-47da-bcab-bc9c1cb67583

Ok.
Exception on client:
Code: 27. DB::ParsingException: Cannot parse input: expected ',' before: '"1"}': While executing ParallelParsingBlockInputFormat: data for INSERT was parsed from query: (at row 1)
. (CANNOT_PARSE_INPUT_ASSERTION_FAILED)

```

### CODE REVIEW

**Comment by Zarathustra2** [comment]
Ah maybe this setting: https://clickhouse.com/docs/en/operations/settings/formats#input_format_json_read_numbers_as_strings

should be turned on by default for insert queries?

**Comment by Zarathustra2** [comment]
is it possible to set a setting per query?

**Comment by sofakingworld** [comment]
If you want to make this setting global, you can add it into Connection struct as `allow_experimental_object_type`

Per query it can be passed as option, for example look up for option `db_side_batch_insertions` 

That options are realized on different modules, I guess some of them may help

**Comment by Zarathustra2** [comment]
@sofakingworld this is now ready

**Comment by sofakingworld** [comment]
@Zarathustra2 Thanks, I'll take a look ASAP

**Comment by sofakingworld** [comment]
All fine, except 1 thing, `add_version` is called so many times, in my case i have 100+ workers to one database. Looks like little N+1

In my opinion, there are 2 possible soluitons:
1. Cache `add_version` 
2. Convert `Connection.new` to function with 2 arity. Second argument is list of options

Something like this 
image


I prefer second solution. What do you think?

**Comment by Zarathustra2** [comment]
Sure I can do that! :)

**Comment by Zarathustra2** [comment]
Though one query per connection start isn't a bad design/issue imo since each of your workers would query the DB anyways no?

**Comment by sofakingworld** [comment]
@Zarathustra2 
I thought a little and finally agree with you

I'll add it to the next release

**Review by sofakingworld — APPROVED** [review]

**Pull request merged**
