### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by likeon**
Bumped mint, tesla and castore dependencies to latest available versions.

Fixes dependency resolution conflict with phoenix 1.7.

p.s. I am Elixir novice and barely understand what I am doing. Tests are passing tho.

### CODE REVIEW

**Comment by sofakingworld** [comment]
I guess, that not bad option to set `>=`, instead of `~>`

Because bumping up special version can break other projects.

make something like this
```
      {:tesla, ">= 1.4.0"},
      {:mint, ">= 1.4.0"},
      {:castore, ">= 0.1.0"},
 ```
 
 Does it help in your case?

**Review by sofakingworld — CHANGES_REQUESTED** [review]
Better change current `~>` to `>=` in mix.exs

**Comment by likeon** [comment]
Yes, works for my case.

Updated the PR as requested:  `>=`, instead of `~>` and rolled back pillar version change.

Thank you.

**Comment by sofakingworld** [comment]
Thank you)

Your fixes will be available in 0.37.0 version

**Pull request merged**
